nepisodes: 10000
nsteps: 500

hopping_mode: true
walking_mode: true

desired_pose:
  x: 10.0
  y: 0.0
  z: 0.7

max_height: 3.0
min_height: 0.30
max_incl: 0.8       
running_step: 0.006  
joint_increment_value: 0.05
done_reward: -50.0
alive_reward: 8.0    
desired_force: 7.08
desired_yaw: 0.0

weight_r1: 1.0
weight_r2: 0.001     
weight_r3: 1.0
weight_r4: 1.0
weight_r5: 1.0
weight_r6: 3.0